name: Trigger auto deployment for next-docker

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/next-docker-AutoDeployTrigger-3b002844-c690-423d-864c-ab6372b12fc3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.NEXTDOCKER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NEXTDOCKER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NEXTDOCKER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: nextdocker0528f7.azurecr.io
          registryUsername: ${{ secrets.NEXTDOCKER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NEXTDOCKER_REGISTRY_PASSWORD }}
          containerAppName: next-docker
          resourceGroup: next-docker
          imageToBuild: nextdocker0528f7.azurecr.io/next-docker:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


